import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import useTrans from '../libs/hooks/useTrans'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const t = useTrans();
  const router = useRouter();

  const changeLang = (lang: string) => {
      router.push(router.asPath, router.asPath, { locale: lang })
      // router.push('/', '/', { locale: lang })
  }

  const handleClick = () => {
    console.log('router:', router);
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        blog
        {t.common.a.b.c}
        <button onClick={handleClick}>show router</button>
        <button onClick={() => changeLang('vi')} >vi</button>
        <button onClick={() => changeLang('en')}>en</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
